use_frameworks!

target 'RYEmptyView_Example' do
  pod 'RYEmptyView', :path => '../'

  target 'RYEmptyView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
